name: flutter_taskhub
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  table_calendar: ^3.1.2
  animations: ^2.0.5
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.2
  # Notification system dependencies
  provider: ^6.1.2
  http: ^1.2.0
  logging: ^1.2.0
  supabase_flutter: ^2.6.0
  jitsi_meet_flutter_sdk: ^11.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logotask.svg
    - assets/icongoogle.svg
